addpath('/users/bphan/bin/MATLAB/cellsegm/',...
    '/users/bphan/tcf4/hc_imaging/',...
    ['/users/bphan/bin/MATLAB/MATLAB_Control_ZEN_from_MATLAB/'...
    'MATLAB_Control_ZEN_from_MATLAB'],...
    '/users/bphan/bin/MATLAB/bfmatlab')
